site_name: Oh Daw!  
repo_url: https://github.com/jaimeranchal/ohdaw 
site_description: Notas de un desarrollador web
site_author: Jaime Ranchal

nav:
    - Principal:  'index.md'
    - Lenguajes:
        - HTML: 
            - Presentación: 'Lenguajes/html/intro.md'
            - Aplicar estilos: 'Lenguajes/html/aspecto.md'
            - Avanzado: 'Lenguajes/html/avanzado.md'
        - CSS: 
            - Presentación: 'Lenguajes/css/intro.md'
            - Optimización: 'Lenguajes/css/optimizacion.md'
            - Preprocesadores: 'Lenguajes/css/preprocesadores.md'
        - Java: 
            - Presentación: 'Lenguajes/java/intro.md'
            - 'Ejemplo de programa': 'Lenguajes/java/ejemplo00.md'
            - 'Conceptos básicos':
                - Sintaxis: 'Lenguajes/java/01.sintaxis.md'
                - 'Tipos de datos': 'Lenguajes/java/02.tipos.md'
                - Estructuras: 'Lenguajes/java/03.estructuras.md'
                - 'Objetos y clases': 'Lenguajes/java/04.objetos-clases.md'
                - Consejos: 'Lenguajes/java/consejos.md'
        - JavaScript: 
            - 'Lo básico':
                - Introducción: 'Lenguajes/javascript/intro.md'
                - Estructura: 'Lenguajes/javascript/estructura.md'
                - Variables: 'Lenguajes/javascript/variables.md'
                - 'Tipos de datos': 'Lenguajes/javascript/tipos.md'
                - 'Operadores básicos': 'Lenguajes/javascript/operadores.md'
                - Comparaciones: 'Lenguajes/javascript/comparar.md'
                - 'Unión de nulos': 'Lenguajes/javascript/operador-nullish-coalescing.md'
                - 'Operadores lógicos': 'Lenguajes/javascript/logic.md'
                - Condicionales: 'Lenguajes/javascript/condicionales.md'
                - 'Sentencias switch': 'Lenguajes/javascript/switch.md'
                - Funciones: 'Lenguajes/javascript/funciones.md'
    - Sistemas:
        - Linux: 
            - Sistema: 'Sistemas/linux/sysadmin.md'
            - Usuarios: 'Sistemas/linux/useradmin.md'
            - Redes: 'Sistemas/linux/netadmin.md'
        - Windows: 
            - Sistema: 'Sistemas/windows/sysadmin.md'
            - Usuarios: 'Sistemas/windows/useradmin.md'
            - Redes: 'Sistemas/windows/netadmin.md'

    - Herramientas: 
        - Contenedores: 
            - Docker: 'Herramientas/docker.md' 
            - Kubernetes: 'Herramientas/kubernetes.md' 
            - Snaps: 'Herramientas/snap.md' 
        - Editores:
            - Vim: 'Herramientas/Editores/vim.md'
            - Visual Studio Code: 'Herramientas/Editores/vscode.md'
            - Sublime Text: 'Herramientas/Editores/sublime-text.md'
        - Frameworks:
            - Laravel: 'Herramientas/Frameworks/laravel.md'
        - IDEs:
            - Apache Netbeans: 'Herramientas/IDE/netbeans.md'
            - Eclipse: 'Herramientas/IDE/eclipse.md'
        - Otros:
            - Maven: 'Herramientas/Otros/maven.md'
    - FAQ: 'FAQ/faq.md'
theme:
    name: material
    language: es
    font:
        text: Noto Sans
        code: Fira Code
    icon:
        logo: material/book-open-blank-variant
    palette:
        scheme: slate
        primary: amber
        accent: deep orange
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.snippets
