site_name: Oh Daw!  
repo_url: https://github.com/jaimeranchal/ohdaw 
site_description: Notas de un desarrollador web
site_author: Jaime Ranchal

# Ajustes del tema
theme:
    language: es
    name: material
    features:
        - navigation.tabs # 'tabs' en versiones más recientes
    palette:
        scheme: default
        primary: deep purple
        accent: indigo
    font:
        text: Rubik
        code: Fira Code
    icon:
        logo: material/book-open-blank-variant

# Extensiones
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - def_list
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.tabbed
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.snippets:
        base_path: '/home/jaime/Proyectos/ohdaw/docs/'
        check_paths: true
# Plugins
plugins:
    - search
    - print-site

# Extra
extra_css:
    - stylesheets/extra.css

# Árbol de documentos
nav:
    - 'Guías rápidas':
        - Laravel:
            - Escoge tu combo: 'gr.laravel-intro.md'
            - Breeze: 'gr.laravel-breeze.md'
            - Mix: 'gr.laravel-mix.md'
        - VueJS con node: 'gr.vuejs-node.md'
    - FAQ: 
        - Qué es una aplicación web: 'faq.apps.md'
        - Diseccionando una web: 'faq.partes-web.md'
        - Del servidor a tu pantalla: 'faq.servicio-web.md'
        - Frameworks: 'faq.frameworks.md'
        - Formularios: 'faq.formularios.md'
        - Seguridad básica: 'faq.usuarios-contraseñas.md'
        - Sesiones y cookies: 'faq.datos-privacidad.md'
    - Fuentes: 'fuentes.md'
